import type { Metadata } from "next";
import "./globals.css";
import Modal from "@/components/AddTask/Modal";
import { KindeProvider } from "@kinde-oss/kinde-auth-react";
import Providers from "@/components/Providers";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

export const metadata: Metadata = {
  title: "Plan Deck",
  description: "Generated by Hussain Rizvi",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  return (
    <html
      lang="en"
      className="scrollbar-thin
    scrollbar-thumb-gray-300 scrollbar-track-gray-100
    scrollbar-thumb-rounded-full scrollbar-track-rounded-full"
    >
      <Providers>
        {" "}
        <Modal user={user} />
        <body className="bg-[#d6e1f6]">{children}</body>
      </Providers>
    </html>
  );
}
